/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { type QueryContext, type CrudContract, type PermissionCheckerContext } from "@zenstackhq/runtime";
import { allFieldsEqual } from "@zenstackhq/runtime/validation";
import { type PolicyDef, type PermissionCheckerConstraint } from "@zenstackhq/runtime/enhancements/node";
import { UserRole } from "../generated/prisma";
import { ClientType } from "../generated/prisma";
import { CargoType } from "../generated/prisma";
import { TransportMode } from "../generated/prisma";
import { Priority } from "../generated/prisma";
import { ShipmentStatus } from "../generated/prisma";
import { PickupStatus } from "../generated/prisma";
import { PickupTimeSlot } from "../generated/prisma";
import { PurchaseStatus } from "../generated/prisma";
import { DeliveryMode } from "../generated/prisma";
import { QuoteStatus } from "../generated/prisma";
import { QuotePaymentMethod } from "../generated/prisma";
import { ProspectStatus } from "../generated/prisma";
import { NotificationType } from "../generated/prisma";
import { DocumentType } from "../generated/prisma";

const policy: PolicyDef = {
    policy: {
        user: {
            modelLevel: {
                read: { guard: User_read, },
                create: { guard: User_create, inputChecker: User_create_input, },
                update: { guard: User_update, },
                postUpdate: { guard: User_postUpdate, },
                delete: { guard: User_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        account: {
            modelLevel: {
                read: { guard: Account_read, },
                create: { guard: Account_create, },
                update: { guard: Account_update, },
                postUpdate: { guard: Account_postUpdate, },
                delete: { guard: Account_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        session: {
            modelLevel: {
                read: { guard: Session_read, },
                create: { guard: Session_create, },
                update: { guard: Session_update, },
                postUpdate: { guard: Session_postUpdate, },
                delete: { guard: Session_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        verificationToken: {
            modelLevel: {
                read: { guard: VerificationToken_read, },
                create: { guard: VerificationToken_create, inputChecker: VerificationToken_create_input, },
                update: { guard: VerificationToken_update, },
                postUpdate: { guard: VerificationToken_postUpdate, },
                delete: { guard: VerificationToken_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        verification: {
            modelLevel: {
                read: { guard: Verification_read, },
                create: { guard: Verification_create, inputChecker: Verification_create_input, },
                update: { guard: Verification_update, },
                postUpdate: { guard: Verification_postUpdate, },
                delete: { guard: Verification_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        client: {
            modelLevel: {
                read: { guard: Client_read, },
                create: { guard: Client_create, inputChecker: Client_create_input, },
                update: { guard: Client_update, },
                postUpdate: { guard: Client_postUpdate, },
                delete: { guard: Client_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        shipment: {
            modelLevel: {
                read: { guard: Shipment_read, },
                create: { guard: Shipment_create, inputChecker: Shipment_create_input, },
                update: { guard: Shipment_update, },
                postUpdate: { guard: Shipment_postUpdate, },
                delete: { guard: Shipment_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        pickupRequest: {
            modelLevel: {
                read: { guard: PickupRequest_read, },
                create: { guard: PickupRequest_create, inputChecker: PickupRequest_create_input, },
                update: { guard: PickupRequest_update, },
                postUpdate: { guard: PickupRequest_postUpdate, },
                delete: { guard: PickupRequest_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        pickupLog: {
            modelLevel: {
                read: { guard: PickupLog_read, },
                create: { guard: PickupLog_create, inputChecker: PickupLog_create_input, },
                update: { guard: PickupLog_update, },
                postUpdate: { guard: PickupLog_postUpdate, },
                delete: { guard: PickupLog_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        purchaseRequest: {
            modelLevel: {
                read: { guard: PurchaseRequest_read, },
                create: { guard: PurchaseRequest_create, inputChecker: PurchaseRequest_create_input, },
                update: { guard: PurchaseRequest_update, },
                postUpdate: { guard: PurchaseRequest_postUpdate, },
                delete: { guard: PurchaseRequest_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        purchaseLog: {
            modelLevel: {
                read: { guard: PurchaseLog_read, },
                create: { guard: PurchaseLog_create, inputChecker: PurchaseLog_create_input, },
                update: { guard: PurchaseLog_update, },
                postUpdate: { guard: PurchaseLog_postUpdate, },
                delete: { guard: PurchaseLog_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        trackingEvent: {
            modelLevel: {
                read: { guard: TrackingEvent_read, },
                create: { guard: TrackingEvent_create, inputChecker: TrackingEvent_create_input, },
                update: { guard: TrackingEvent_update, },
                postUpdate: { guard: TrackingEvent_postUpdate, },
                delete: { guard: TrackingEvent_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        shipmentLog: {
            modelLevel: {
                read: { guard: ShipmentLog_read, },
                create: { guard: ShipmentLog_create, inputChecker: ShipmentLog_create_input, },
                update: { guard: ShipmentLog_update, },
                postUpdate: { guard: ShipmentLog_postUpdate, },
                delete: { guard: ShipmentLog_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        quote: {
            modelLevel: {
                read: { guard: Quote_read, },
                create: { guard: Quote_create, },
                update: { guard: Quote_update, },
                postUpdate: { guard: Quote_postUpdate, },
                delete: { guard: Quote_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        quoteLog: {
            modelLevel: {
                read: { guard: QuoteLog_read, },
                create: { guard: QuoteLog_create, inputChecker: QuoteLog_create_input, },
                update: { guard: QuoteLog_update, },
                postUpdate: { guard: QuoteLog_postUpdate, },
                delete: { guard: QuoteLog_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        prospect: {
            modelLevel: {
                read: { guard: Prospect_read, },
                create: { guard: Prospect_create, inputChecker: Prospect_create_input, },
                update: { guard: Prospect_update, },
                postUpdate: { guard: Prospect_postUpdate, },
                delete: { guard: Prospect_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        notification: {
            modelLevel: {
                read: { guard: Notification_read, },
                create: { guard: Notification_create, inputChecker: Notification_create_input, },
                update: { guard: Notification_update, },
                postUpdate: { guard: Notification_postUpdate, },
                delete: { guard: Notification_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        document: {
            modelLevel: {
                read: { guard: Document_read, },
                create: { guard: Document_create, },
                update: { guard: Document_update, },
                postUpdate: { guard: Document_postUpdate, },
                delete: { guard: Document_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        pricingConfig: {
            modelLevel: {
                read: { guard: PricingConfig_read, },
                create: { guard: PricingConfig_create, inputChecker: PricingConfig_create_input, },
                update: { guard: PricingConfig_update, },
                postUpdate: { guard: PricingConfig_postUpdate, },
                delete: { guard: PricingConfig_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        countryDistance: {
            modelLevel: {
                read: { guard: CountryDistance_read, },
                create: { guard: CountryDistance_create, inputChecker: CountryDistance_create_input, },
                update: { guard: CountryDistance_update, },
                postUpdate: { guard: CountryDistance_postUpdate, },
                delete: { guard: CountryDistance_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        transportRate: {
            modelLevel: {
                read: { guard: TransportRate_read, },
                create: { guard: TransportRate_create, inputChecker: TransportRate_create_input, },
                update: { guard: TransportRate_update, },
                postUpdate: { guard: TransportRate_postUpdate, },
                delete: { guard: TransportRate_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        country: {
            modelLevel: {
                read: { guard: Country_read, },
                create: { guard: Country_create, inputChecker: Country_create_input, },
                update: { guard: Country_update, },
                postUpdate: { guard: Country_postUpdate, },
                delete: { guard: Country_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        systemConfig: {
            modelLevel: {
                read: { guard: SystemConfig_read, },
                create: { guard: SystemConfig_create, inputChecker: SystemConfig_create_input, },
                update: { guard: SystemConfig_update, },
                postUpdate: { guard: SystemConfig_postUpdate, },
                delete: { guard: SystemConfig_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
    },
    validation: {
        user: { hasValidation: false },
        account: { hasValidation: false },
        session: { hasValidation: false },
        verificationToken: { hasValidation: false },
        verification: { hasValidation: false },
        client: { hasValidation: false },
        shipment: { hasValidation: false },
        pickupRequest: { hasValidation: false },
        pickupLog: { hasValidation: false },
        purchaseRequest: { hasValidation: false },
        purchaseLog: { hasValidation: false },
        trackingEvent: { hasValidation: false },
        shipmentLog: { hasValidation: false },
        quote: { hasValidation: false },
        quoteLog: { hasValidation: false },
        prospect: { hasValidation: false },
        notification: { hasValidation: false },
        document: { hasValidation: false },
        pricingConfig: { hasValidation: false },
        countryDistance: { hasValidation: false },
        transportRate: { hasValidation: false },
        country: { hasValidation: false },
        systemConfig: { hasValidation: false },
    },
    authSelector: { "role": true, "id": true, "clientId": true },
};

function User_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_User_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.id == input?.id)) { return true; }

    if (((user?.clientId == input?.clientId) && ((user?.role == UserRole.OPERATIONS_MANAGER) || (user?.role == UserRole.FINANCE_MANAGER)))) { return true; }

    return false;
}

function User_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_User_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function User_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && ((user?.role == UserRole.ADMIN))
}

function User_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_User_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.id == input?.id)) { return true; }

    return false;
}

function User_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_User_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function User_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_User_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Account_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Account_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.id == input?.userId)) { return true; }

    return false;
}

function Account_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Account_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.id == input?.userId)) { return true; }

    return false;
}

function Account_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Account_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.id == input?.userId)) { return true; }

    return false;
}

function Account_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Account_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Account_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Account_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.id == input?.userId)) { return true; }

    return false;
}

function Session_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Session_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.id == input?.userId)) { return true; }

    return false;
}

function Session_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Session_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.id == input?.userId)) { return true; }

    return false;
}

function Session_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Session_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.id == input?.userId)) { return true; }

    return false;
}

function Session_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Session_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Session_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Session_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.id == input?.userId)) { return true; }

    return false;
}

function VerificationToken_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_VerificationToken_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if (true) { return true; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function VerificationToken_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_VerificationToken_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function VerificationToken_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && ((user?.role == UserRole.ADMIN))
}

function VerificationToken_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_VerificationToken_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function VerificationToken_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_VerificationToken_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function VerificationToken_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_VerificationToken_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Verification_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Verification_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if (true) { return true; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Verification_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Verification_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Verification_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && ((user?.role == UserRole.ADMIN))
}

function Verification_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Verification_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Verification_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Verification_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Verification_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Verification_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Client_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Client_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if (((user?.role == UserRole.OPERATIONS_MANAGER) || (user?.role == UserRole.FINANCE_MANAGER))) { return true; }

    if ((user?.clientId == input?.id)) { return true; }

    return false;
}

function Client_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Client_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Client_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && ((user?.role == UserRole.ADMIN))
}

function Client_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Client_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.clientId == input?.id)) { return true; }

    return false;
}

function Client_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Client_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Client_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Client_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Shipment_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Shipment_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if ((user?.role == UserRole.FINANCE_MANAGER)) { return true; }

    if ((((input?.clientId != null) && (user?.clientId == input?.clientId)) && (user?.role == UserRole.CLIENT))) { return true; }

    if (((user?.id == input?.createdById) && (input?.status != ShipmentStatus.DELIVERED))) { return true; }

    return false;
}

function Shipment_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Shipment_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function Shipment_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && ((user?.role == UserRole.ADMIN) || (user?.role == UserRole.OPERATIONS_MANAGER))
}

function Shipment_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Shipment_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if (((user?.id == input?.createdById) && (input?.status != ShipmentStatus.DELIVERED))) { return true; }

    return false;
}

function Shipment_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Shipment_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Shipment_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Shipment_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function PickupRequest_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PickupRequest_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if ((user?.role == UserRole.FINANCE_MANAGER)) { return true; }

    if (((((input?.userId != null) && (user?.id == input?.userId)) && (input?.status != PickupStatus.EFFECTUE)) && (input?.status != PickupStatus.ANNULE))) { return true; }

    if (((user?.clientId == input?.clientId) && (user?.role == UserRole.CLIENT))) { return true; }

    return false;
}

function PickupRequest_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PickupRequest_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if (true) { return true; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function PickupRequest_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && (true || (user?.role == UserRole.ADMIN) || (user?.role == UserRole.OPERATIONS_MANAGER))
}

function PickupRequest_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PickupRequest_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if (((((input?.userId != null) && (user?.id == input?.userId)) && (input?.status != PickupStatus.EFFECTUE)) && (input?.status != PickupStatus.ANNULE))) { return true; }

    return false;
}

function PickupRequest_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_PickupRequest_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function PickupRequest_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PickupRequest_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function PickupLog_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PickupLog_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if ((user?.role == UserRole.FINANCE_MANAGER)) { return true; }

    if ((user?.id == input?.pickup?.userId)) { return true; }

    return false;
}

function PickupLog_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PickupLog_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function PickupLog_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && ((user?.role == UserRole.ADMIN) || (user?.role == UserRole.OPERATIONS_MANAGER))
}

function PickupLog_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PickupLog_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function PickupLog_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_PickupLog_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function PickupLog_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PickupLog_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function PurchaseRequest_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PurchaseRequest_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if ((user?.role == UserRole.FINANCE_MANAGER)) { return true; }

    if (((((input?.userId != null) && (user?.id == input?.userId)) && (input?.status != PurchaseStatus.LIVRE)) && (input?.status != PickupStatus.ANNULE))) { return true; }

    if (((user?.clientId == input?.clientId) && (user?.role == UserRole.CLIENT))) { return true; }

    return false;
}

function PurchaseRequest_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PurchaseRequest_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if (true) { return true; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function PurchaseRequest_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && (true || (user?.role == UserRole.ADMIN) || (user?.role == UserRole.OPERATIONS_MANAGER))
}

function PurchaseRequest_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PurchaseRequest_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if (((((input?.userId != null) && (user?.id == input?.userId)) && (input?.status != PurchaseStatus.LIVRE)) && (input?.status != PickupStatus.ANNULE))) { return true; }

    return false;
}

function PurchaseRequest_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_PurchaseRequest_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function PurchaseRequest_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PurchaseRequest_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function PurchaseLog_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PurchaseLog_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if ((user?.role == UserRole.FINANCE_MANAGER)) { return true; }

    if ((user?.id == input?.purchase?.userId)) { return true; }

    return false;
}

function PurchaseLog_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PurchaseLog_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function PurchaseLog_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && ((user?.role == UserRole.ADMIN) || (user?.role == UserRole.OPERATIONS_MANAGER))
}

function PurchaseLog_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PurchaseLog_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function PurchaseLog_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_PurchaseLog_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function PurchaseLog_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PurchaseLog_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function TrackingEvent_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_TrackingEvent_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if ((user?.clientId == input?.shipment?.clientId)) { return true; }

    return false;
}

function TrackingEvent_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_TrackingEvent_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function TrackingEvent_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && ((user?.role == UserRole.ADMIN) || (user?.role == UserRole.OPERATIONS_MANAGER))
}

function TrackingEvent_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_TrackingEvent_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function TrackingEvent_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_TrackingEvent_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function TrackingEvent_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_TrackingEvent_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function ShipmentLog_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_ShipmentLog_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if ((user?.role == UserRole.FINANCE_MANAGER)) { return true; }

    if ((user?.id == input?.shipment?.createdById)) { return true; }

    if (((user?.clientId == input?.shipment?.clientId) && (user?.role == UserRole.CLIENT))) { return true; }

    return false;
}

function ShipmentLog_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_ShipmentLog_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function ShipmentLog_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && ((user?.role == UserRole.ADMIN) || (user?.role == UserRole.OPERATIONS_MANAGER))
}

function ShipmentLog_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_ShipmentLog_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function ShipmentLog_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_ShipmentLog_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function ShipmentLog_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_ShipmentLog_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Quote_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Quote_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if ((user?.role == UserRole.FINANCE_MANAGER)) { return true; }

    if ((((input?.clientId != null) && (user?.clientId == input?.clientId)) && (user?.role == UserRole.CLIENT))) { return true; }

    if (((input?.userId != null) && (user?.id == input?.userId))) { return true; }

    return false;
}

function Quote_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Quote_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if (true) { return true; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if ((((input?.clientId != null) && (user?.clientId == input?.clientId)) && (user?.role == UserRole.CLIENT))) { return true; }

    return false;
}

function Quote_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Quote_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if (((input?.userId != null) && (user?.id == input?.userId))) { return true; }

    return false;
}

function Quote_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Quote_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Quote_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Quote_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function QuoteLog_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_QuoteLog_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if ((user?.role == UserRole.FINANCE_MANAGER)) { return true; }

    if ((user?.id == input?.quote?.userId)) { return true; }

    if ((((input?.quote?.clientId != null) && (user?.clientId == input?.quote?.clientId)) && (user?.role == UserRole.CLIENT))) { return true; }

    return false;
}

function QuoteLog_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_QuoteLog_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function QuoteLog_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && ((user?.role == UserRole.ADMIN) || (user?.role == UserRole.OPERATIONS_MANAGER))
}

function QuoteLog_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_QuoteLog_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function QuoteLog_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_QuoteLog_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function QuoteLog_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_QuoteLog_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function Prospect_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Prospect_read(input: any, context: QueryContext): any {
    if (true) { return false; }

    if (true) { return true; }

    return false;
}

function Prospect_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Prospect_create(input: any, context: QueryContext): any {
    if (true) { return false; }

    if (true) { return true; }

    return false;
}

function Prospect_create_input(input: any, context: QueryContext): boolean {
    return !(true) && (true)
}

function Prospect_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Prospect_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Prospect_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Prospect_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Prospect_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Prospect_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Notification_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Notification_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.id == input?.userId)) { return true; }

    return false;
}

function Notification_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Notification_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    return false;
}

function Notification_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && ((user?.role == UserRole.ADMIN) || (user?.role == UserRole.OPERATIONS_MANAGER))
}

function Notification_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Notification_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.id == input?.userId)) { return true; }

    return false;
}

function Notification_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Notification_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Notification_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Notification_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Document_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Document_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if ((user?.role == UserRole.FINANCE_MANAGER)) { return true; }

    if ((((input?.clientId != null) && (user?.clientId == input?.clientId)) && (user?.role == UserRole.CLIENT))) { return true; }

    if (((input?.userId != null) && (user?.id == input?.userId))) { return true; }

    return false;
}

function Document_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Document_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if ((((input?.clientId != null) && (user?.clientId == input?.clientId)) && (user?.role == UserRole.CLIENT))) { return true; }

    if (((input?.userId != null) && (user?.id == input?.userId))) { return true; }

    return false;
}

function Document_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Document_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Document_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Document_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Document_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Document_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    if ((user?.role == UserRole.OPERATIONS_MANAGER)) { return true; }

    if ((user?.id == input?.uploadedBy)) { return true; }

    return false;
}

function PricingConfig_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PricingConfig_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function PricingConfig_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PricingConfig_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function PricingConfig_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && ((user?.role == UserRole.ADMIN))
}

function PricingConfig_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PricingConfig_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function PricingConfig_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_PricingConfig_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function PricingConfig_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PricingConfig_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function CountryDistance_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_CountryDistance_read(input: any, context: QueryContext): any {
    if (true) { return false; }

    if (true) { return true; }

    return false;
}

function CountryDistance_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_CountryDistance_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function CountryDistance_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !(true) && ((user?.role == UserRole.ADMIN))
}

function CountryDistance_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_CountryDistance_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function CountryDistance_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_CountryDistance_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function CountryDistance_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_CountryDistance_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function TransportRate_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_TransportRate_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (true) { return true; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function TransportRate_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    if ((user?.role == UserRole.ADMIN)) { return { AND: [] }; } return { OR: [] };
}

function $check_TransportRate_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function TransportRate_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return (user?.role == UserRole.ADMIN)
}

function TransportRate_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    if ((user?.role == UserRole.ADMIN)) { return { AND: [] }; } return { OR: [] };
}

function $check_TransportRate_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function TransportRate_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_TransportRate_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function TransportRate_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    if ((user?.role == UserRole.ADMIN)) { return { AND: [] }; } return { OR: [] };
}

function $check_TransportRate_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Country_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    if ((user == null)) { return { OR: [] }; } if (true) { return { AND: [] }; } return { OR: [] };
}

function $check_Country_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((user == null)) { return false; }

    if (true) { return true; }

    return false;
}

function Country_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    if ((user == null)) { return { OR: [] }; } if ((user?.role == UserRole.ADMIN)) { return { AND: [] }; } return { OR: [] };
}

function $check_Country_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((user == null)) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Country_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return !((user == null)) && ((user?.role == UserRole.ADMIN))
}

function Country_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    if ((user == null)) { return { OR: [] }; } if ((user?.role == UserRole.ADMIN)) { return { AND: [] }; } return { OR: [] };
}

function $check_Country_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((user == null)) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function Country_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Country_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Country_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    if ((user == null)) { return { OR: [] }; } if ((user?.role == UserRole.ADMIN)) { return { AND: [] }; } return { OR: [] };
}

function $check_Country_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((user == null)) { return false; }

    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function SystemConfig_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_SystemConfig_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function SystemConfig_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    if ((user?.role == UserRole.ADMIN)) { return { AND: [] }; } return { OR: [] };
}

function $check_SystemConfig_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function SystemConfig_create_input(input: any, context: QueryContext): boolean {
    const user: any = context.user ?? null;
    return (user?.role == UserRole.ADMIN)
}

function SystemConfig_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    if ((user?.role == UserRole.ADMIN)) { return { AND: [] }; } return { OR: [] };
}

function $check_SystemConfig_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}

function SystemConfig_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_SystemConfig_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function SystemConfig_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    if ((user?.role == UserRole.ADMIN)) { return { AND: [] }; } return { OR: [] };
}

function $check_SystemConfig_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((user?.role == UserRole.ADMIN)) { return true; }

    return false;
}
export default policy
